name: meetingmetric
version: "1.0.0"
config-version: 2

profile: meetingmetric

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: target
clean-targets: ["target", "dbt_packages"]

models:
  meetingmetric:
    staging:
      +materialized: view
      +tags: ["staging"]
    marts:
      +materialized: table
      +tags: ["gold"]
